version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6000:6379"

  definitions-db:
    image: postgres:15
    container_name: definitions-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: definitions
    ports:
      - '5003:5432'
    volumes:
      - definitions-db-data:/var/lib/postgresql/data

  states-db:
    image: postgres:15
    container_name: states-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: states
    ports:
      - '5004:5432'
    volumes:
      - states-db-data:/var/lib/postgresql/data



volumes:
  definitions-db-data:
  states-db-data:
  # server-a:
  #   build: ./server-a
  #   container_name: server-a
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

  # server-b:
  #   build: ./server-b
  #   # deploy:
  #     # replicas: 3  # Run 3 replicas of Server B
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
