version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # server-a:
  #   build: ./server-a
  #   container_name: server-a
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

  # server-b:
  #   build: ./server-b
  #   # deploy:
  #     # replicas: 3  # Run 3 replicas of Server B
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
