export enum Status {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_FOR_DEPENDENCY = 'WAITING_FOR_DEPENDENCY',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
  SUCCEEDED = 'SUCCEEDED',
  CANCELED = 'CANCELED',
}
